version: '3.2'

services:

  frontend:
    build: docker/frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.229.1 remote_port=9009 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - db
    depends_on:
      - db
    networks:
      - internal

  backend:
    build:
      context: docker/backend

    ports:
      - 22080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.229.1 remote_port=9009 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    links:
      - db
    depends_on:
      - db
    networks:
      - internal

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=Z4SZX7PdXg
      - MYSQL_DATABASE=portfolio
      - MYSQL_USER=portfolio_user
      - MYSQL_PASSWORD=123456
    restart: always
    volumes:
      - ./database/data1:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - internal

  myadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 91:80
    networks:
      - internal

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.229.0/28